# Generated by Django 2.0.4 on 2018-05-25 22:07

from django.db import migrations

def add_attributes(apps, schema_editor):
    TemplateAttribute = apps.get_model('settings', 'TemplateAttribute')

    attributes = [
        {'name': 'width', 'code': '%(width)d', 'description': 'Width of the video'},
        {'name': 'height', 'code': '%(height)d', 'description': 'Height of the video'},
        {'name': 'tbr', 'code': '%(tbr)d', 'description': 'Average bitrate of audio and video in KBit/s'},
        {'name': 'abr', 'code': '%(abr)d', 'description': 'Average audio bitrate in KBit/s'},
        {'name': 'asr', 'code': '%(asr)d', 'description': 'Audio sampling rate in Hertz'},
        {'name': 'vbr', 'code': '%(vbr)d', 'description': 'Average video bitrate in KBit/s'},
        {'name': 'fps', 'code': '%(fps)d', 'description': 'Frame rate'},
        {'name': 'filesize', 'code': '%(filesize)d', 'description': 'The number of bytes, if known in advance'},
        {'name': 'filesize_approx', 'code': '%(filesize_approx)d', 'description': 'An estimate for the number of bytes'},
        {'name': 'timestamp', 'code': '%(timestamp)d', 'description': 'UNIX timestamp of the moment the video became available'},
        {'name': 'duration', 'code': '%(duration)d', 'description': 'Length of the video in seconds'},
        {'name': 'view_count', 'code': '%(view_count)d', 'description': 'How many users have watched the video on the platform'},
        {'name': 'like_count', 'code': '%(like_count)d', 'description': 'Number of positive ratings of the video'},
        {'name': 'dislike_count', 'code': '%(dislike_count)d', 'description': ' Number of negative ratings of the video'},
        {'name': 'repost_count', 'code': '%(repost_coun)d', 'description': 'Number of reposts of the video'},
        {'name': 'average_rating', 'code': '%(average_rating)d', 'description': 'Average rating give by users, the scale used depends on the webpage'},
        {'name': 'comment_count', 'code': '%(comment_count)d', 'description': 'Number of comments on the video'},
        {'name': 'age_limit', 'code': '%(age_limit)d', 'description': 'Age restriction for the video (years)'},
        {'name': 'start_time', 'code': '%(start_time)d', 'description': 'Time in seconds where the reproduction should start, as specified in the UR'},
        {'name': 'end_time', 'code': '%(end_time)d', 'description': 'Time in seconds where the reproduction should end, as specified in the URL'},
        {'name': 'id', 'code': '%(id)s', 'description': 'Video identifier'},
        {'name': 'title', 'code': '%(title)s', 'description': 'Video title'},
        {'name': 'url', 'code': '%(url)s', 'description': 'Video URL'},
        {'name': 'ext', 'code': '%(ext)s', 'description': 'Video filename extension'},
        {'name': 'alt_title', 'code': '%(alt_title)s', 'description': 'A secondary title of the video'},
        {'name': 'display_id', 'code': '%(display_id)s', 'description': 'An alternative identifier for the video'},
        {'name': 'uploader', 'code': '%(uploader)s', 'description': 'Full name of the video uploader'},
        {'name': 'creator', 'code': '%(creator)s', 'description': 'The creator of the video'},
        {'name': 'release_date', 'code': '%(release_date)s', 'description': 'The date (YYYYMMDD) when the video was released'},
        {'name': 'upload_date', 'code': '%(upload_date)s', 'description': 'Video upload date (YYYYMMDD)'},
        {'name': 'uploader_id', 'code': '%(uploader_id)s', 'description': 'Nickanem or id of the video uploader'},
        {'name': 'location', 'code': '%(location)s', 'description': 'Physical location where the video was filmed'},
        {'name': 'format', 'code': '%(format)s', 'description': 'A human-readable description of the format'},
        {'name': 'format_id', 'code': '%(format_id)s', 'description': 'Format code specified by --format'},
        {'name': 'format_note', 'code': '%(format_note)s', 'description': 'Additional info about the format'},
        {'name': 'resolution', 'code': '%(resolution)s', 'description': 'Textual description of width and height'},
        {'name': 'acodec', 'code': '%(acodec)s', 'description': 'Name of the audio coded in use'},
        {'name': 'vcodec', 'code': '%(vcodec)s', 'description': 'Name of the video codec in use'},
        {'name': 'container', 'code': '%(container)s', 'description': 'Name of the container format'},
        {'name': 'protocol', 'code': '%(protocol)s', 'description': 'The protocol that will be used for the actual download'},
        {'name': 'extractor', 'code': '%(extractor)s', 'description': 'Name of the extractor'},
        {'name': 'extractor_key', 'code': '%(extractor_key)s', 'description': 'Key name of the extractor'},
        {'name': 'playlist', 'code': '%(playlist)s', 'description': 'Name or id of the playlist that contains video'},
        {'name': 'playlist_id', 'code': '%(playlist_id)s', 'description': 'Playlist identifier'},
        {'name': 'playlist_index', 'code': '%(playlist_index)d', 'description': ''},
        {'name': 'playlist_title', 'code': '%(playlist_title)s', 'description': 'Playlist title'},
        {'name': 'playlist_uploader', 'code': '%(playlist_uploader)s', 'description': 'Full name of the playlist uploader'},
        {'name': 'playlist_uploader_id', 'code': '%(playlist_uploader_id)s', 'description': 'Nickname or id of the playlist uploader'},
        {'name': 'chapter', 'code': '%(chapter)s', 'description': 'Name or title of the chapter the video belongs to'},
        {'name': 'chapter_number', 'code': '%(chapter_number)d', 'description': 'Number of the chapter the video belongs to'},
        {'name': 'chapter_id', 'code': '%(chapter_id)s', 'description': 'Id of the chapter the video belongs to'},
        {'name': 'series', 'code': '%(series)s', 'description': 'Title of the series or programme the video episode belongs to'},
        {'name': 'season', 'code': '%(season)s', 'description': 'Title of the season the video episode belongs to'},
        {'name': 'season_number', 'code': '%(season_number)d', 'description': 'Number of the season the video episode belongs to'},
        {'name': 'season_id', 'code': '%(season_id)s', 'description': 'Id of the season the video episode belongs to'},
        {'name': 'episode', 'code': '%(episode)s', 'description': 'Title of the video episode'},
        {'name': 'episode_number', 'code': '%(episode_number)d', 'description': ''},
        {'name': 'episode_id', 'code': '%(episode_id)s', 'description': 'Id of the video episode'},
        {'name': 'track', 'code': '%(track)s', 'description': 'Title of the track'},
        {'name': 'track_number', 'code': '%(track_number)d', 'description': 'Number of the track within an album or a disc'},
        {'name': 'track_id', 'code': '%(track_id)s', 'description': 'Id of the track'},
        {'name': 'artist', 'code': '%(artist)s', 'description': 'Artist(s) of the track'},
        {'name': 'genre', 'code': '%(genre)s', 'description': 'Genre(s) of the track'},
        {'name': 'album', 'code': '%(album)s', 'description': 'Title of the album the track belongs to'},
        {'name': 'album_type', 'code': '%(album_type)s', 'description': 'Type of the album'},
        {'name': 'album_artist', 'code': '%(album_artist)s', 'description': 'List of all the artists appeared on the album'},
        {'name': 'disc_number', 'code': '%(disc_number)d', 'description': 'Number of the disc or other physical medium the track belongs to'},
        {'name': 'release_year', 'code': '%(release_year)d', 'description': 'Year (YYYY) when the album was released'},
    ]

    for attr in attributes:
        TemplateAttribute.objects.create(**attr)


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_attributes)
    ]
