# Generated by Django 2.0.4 on 2018-06-04 23:53

from django.db import migrations

def add_attributes(apps, schema_editor):
    TemplateAttribute = apps.get_model('settings', 'TemplateAttribute')

    attributes = [
        {'name': 'database category', 'code': '{category}', 'description': 'Category that comes from the database'},
        {'name': 'database playlist slug', 'code': '{playlist_slug}', 'description': 'Slug of the playlist title saved in the database'},
    ]

    for attr in attributes:
        TemplateAttribute.objects.create(**attr)

class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20180603_1813'),
    ]

    operations = [
        migrations.RunPython(add_attributes)
    ]
