# Generated by Django 2.0.4 on 2018-06-23 22:42

from django.db import migrations

def add_attributes(apps, schema_editor):
    TemplateAttribute = apps.get_model('settings', 'TemplateAttribute')

    attributes = [
        {'name': 'database playlist order', 'code': '{playlist_video_order}', 'description': 'Order for a video in a playlist saved to the database'},
    ]

    for attr in attributes:
        print(attr)
        TemplateAttribute.objects.create(**attr)

class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20180604_2353'),
    ]

    operations = [
        migrations.RunPython(add_attributes)
    ]
