# Generated by Django 2.0.4 on 2018-04-08 18:42

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('in-queue', 'In Queue'), ('completed', 'Completed'), ('error', 'Errored')], default='in-queue', max_length=25)),
                ('target', models.CharField(max_length=1000)),
                ('target_type', models.CharField(choices=[('video', 'Video'), ('youtube', 'YouTube'), ('full30', 'Full 30')], max_length=25)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
