# Generated by Django 2.0.4 on 2018-04-15 20:34

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('in-queue', 'In Queue'), ('completed', 'Completed'), ('error', 'Errored')], default='in-queue', max_length=25)),
                ('target', models.CharField(max_length=1000)),
                ('target_type', models.CharField(choices=[('video', 'Video'), ('youtube', 'YouTube'), ('full30', 'Full 30')], max_length=25)),
                ('title', models.CharField(blank=True, help_text="Should Auto-populate if you don't fill it in.", max_length=500)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title'])),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.VideoCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, help_text="Should Auto-populate if you don't fill it in.", max_length=500),
        ),
    ]
