# Generated by Django 2.0.4 on 2018-05-06 16:49

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_video_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('target', models.CharField(max_length=1000)),
                ('target_type', models.CharField(choices=[('youtube', 'YouTube')], max_length=25)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title'])),
                ('title', models.CharField(blank=True, help_text="Should Auto-populate if you don't fill it in.", max_length=500)),
                ('paused', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.VideoCategory')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='playlist',
            name='target_type',
            field=models.CharField(choices=[('video', 'Video'), ('youtube', 'YouTube')], max_length=25),
        ),
        migrations.AlterField(
            model_name='video',
            name='target_type',
            field=models.CharField(choices=[('video', 'Video'), ('youtube', 'YouTube')], max_length=25),
        ),
    ]
