# Generated by Django 2.0.4 on 2018-05-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20180506_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='download',
            field=models.BooleanField(default=True, help_text='Download all the videos in the playlist when added'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='subscribed',
            field=models.BooleanField(default=False, help_text='Continue to download new vidoes added to this playlist'),
        ),
    ]
