# Generated by Django 2.0.4 on 2018-06-03 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20180603_1813'),
        ('videos', '0008_auto_20180603_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={},
        ),
        migrations.AddField(
            model_name='channel',
            name='name_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.DownloadTemplate'),
        ),
    ]
