# Generated by Django 2.0.4 on 2018-06-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_auto_20180603_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
